### PR TITLE
Shared Community Navigation component on Swag site

### PR DESCRIPTION
**Pull request by zachleat**
Demo: https://deploy-preview-97--swag.netlify.app/

Header uses component from https://github.com/netlify/netlify-ui-community-nav

Second of five properties required to solve: netlify/marketing#1470

### CODE REVIEW

**Comment by tabar** [comment]
screenshot

Can these be a little closer together
<details><summary>Browser metadata</summary>





```
Path:      /
Browser:   Chrome 90.0.4430.212 on Mac OS 10.15.7
Viewport:  1440 x 711 @2x
Language:  en-US
Cookies:   Enabled
```

[View on BrowserStack](https://live.browserstack.com/dashboard#url=https%3A%2F%2Fdeploy-preview-97--swag.netlify.app%2F&os=OS+X&os_version=Catalina&browser=Chrome&browser_version=90.0&resolution=1440x711&speed=1&start=true)



</details>

[Open Deploy Preview](https://deploy-preview-97--swag.netlify.app/) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=60bfcaf48168b40009d6ec38&commentID=60c68075ee6ca308cd90b334&resolution=resolved)

**Comment by zachleat** [comment]
Feedback resolved and applied to all 5 repos 😅

**Review by huguestennier — APPROVED** [review]
Looking good here too! Another small comment we can fix after everything is live, but with a SR the Netlify logo is announced as "home" which should probably be something like `netlify.com` instead. Or `Netlify home`?

**Comment by zachleat** [comment]
Filed https://github.com/netlify/netlify-ui-community-nav/issues/6

**Pull request merged**
